/* eslint-disable react-refresh/only-export-components */
import {
  createContext,
  useContext,
  useEffect,
  useMemo,
  useState,
  type PropsWithChildren,
} from 'react';
import { FUNCTIONAL_MESSAGES } from './functionalMessages';

export const SUPPORTED_LOCALES = [
  { code: 'en', name: 'English' },
  { code: 'zh-CN', name: '中文（简体）' },
  { code: 'zh-TW', name: '中文（繁體）' },
  { code: 'zh-HK', name: '粵語（繁體）' },
  { code: 'ja', name: '日本語' },
  { code: 'ko', name: '한국어' },
  { code: 'es', name: 'Español' },
  { code: 'fr', name: 'Français' },
  { code: 'ru', name: 'Русский' },
  { code: 'de', name: 'Deutsch' },
] as const;

export type AppLocale = (typeof SUPPORTED_LOCALES)[number]['code'];
type MessageKey = keyof typeof EN_MESSAGES;

const EN_MESSAGES = {
  language: 'LANGUAGE',
  player: 'PLAYER',
  tagline: 'Program the arm. Shape the haircut. Beat the clock.',
  tutorial: 'Tutorial',
  tutorialBody: 'Learn Grid paths, Servo Angles, and how the two control levels connect.',
  learn: 'Learn →',
  lessons: 'Lessons',
  lessonsBody: 'Ten Cutter Grid and eight Servo Angles lessons with required quizzes and Blockly practice.',
  practise: 'Practice →',
  solo: 'Solo Practice',
  soloBody: 'Finish one challenge and the next adapts to how you are doing.',
  start: 'Start →',
  versus: 'Versus Round',
  versusBody: 'Everyone gets the same hairstyle and time limit. Closest to the target wins.',
  play: 'Play →',
  backendConnected: 'BACKEND CONNECTED',
  offlinePractice: 'OFFLINE · PRACTICE',
  defaultChallengeName: 'Crown Trim',
  defaultChallengeDescription: 'Remove the eleven highlighted crown voxels and leave the rest untouched. All five hardware servos start at 90°. Move X · Base Yaw from 90° to 150°; keep Y, Z, B, and E at Home. The lessons break this sweep into smaller steps.',
  requiredData: 'Online scoring sends your compiled Blockly program, challenge and score data to the server. This is required to score the run.',
  researchChoice: 'Allow my submitted programs, scores, primary language and coarse UTC offset to be used in de-identified learning research.',
  researchHint: 'Primary language and UTC offset can be disabled separately in More settings. No browser fingerprint or precise time-zone name is collected.',
  dataSettings: 'Data settings',
  privacyTitle: 'Your data choices',
  privacyIntro: 'The simulator needs some data to provide online scoring. De-identified research use is a separate choice.',
  necessaryTitle: 'Necessary scoring data',
  necessaryBody: 'Compiled Blockly program, challenge version and score. Always on for online Practice and Versus.',
  optionalTitle: 'Optional learning research',
  optionalBody: 'Submitted programs and scores plus primary language and coarse UTC offset. No browser fingerprint or precise time-zone name.',
  necessaryOnly: 'Necessary only',
  acceptResearch: 'Allow research',
  moreSettings: 'More settings',
  saveSettings: 'Save settings',
  notNow: 'Not now',
  allowAllResearch: 'Allow all research',
  programResearchTitle: 'Programs and scores',
  programResearchBody: 'Allow submitted Blockly IR and resulting scores to enter the de-identified research dataset.',
  languageResearchTitle: 'Primary language',
  languageResearchBody: 'Share only a coarse primary code such as zh or en.',
  timezoneResearchTitle: 'UTC offset',
  timezoneResearchBody: 'Share only the current minute offset, not a precise time-zone name.',
  neverCollected: 'Browser fingerprints are never collected.',
  participateStudy: 'Participate in the academic study',
  exitStudy: 'Exit',
  studyTitle: 'Academic research participation',
  studyIntro: 'HCR is an academic study of how people learn robot programming. Review the data choices below, then choose whether to take part.',
  studyDeclinedTitle: 'You chose not to participate',
  studyDeclinedBody: 'No simulator session or player identifier has been created. You can close this page or review the study information again.',
  reviewStudy: 'Review study information',
  closeApplication: 'Close application',
  menu: 'Menu',
  back: 'Back',
  backToMenu: 'Back to Menu',
  challenge: 'CHALLENGE',
  program: 'PROGRAM',
  programPanel: 'Blockly program panel',
  programIr: 'PROGRAM IR',
  blocks: 'BLOCKS',
  inspector: 'INSPECTOR',
  simulationStatus: 'Simulation Status',
  cameraOrbit: 'CAMERA / ORBIT',
  local: 'LOCAL',
  programError: 'PROGRAM ERROR',
  retry: 'Retry',
  webglUnsupported: 'This browser does not support WebGL. Please use the latest version of Chrome or Edge.',
  collapseProgram: 'Collapse program panel',
  expandProgram: 'Expand program panel',
  collapseInspector: 'Collapse status panel',
  expandInspector: 'Expand status panel',
  programmingMode: 'Programming mode',
  servoAnglesMode: 'Servo Angles',
  cutterGridMode: 'Cutter Grid',
  servoAnglesProgram: 'Servo Angles Program',
  cutterGridProgram: 'Cutter Grid Program',
  simulationControls: 'Simulation controls',
  test: 'Test',
  run: 'Run',
  resume: 'Resume',
  pause: 'Pause',
  step: 'Step',
  stop: 'Stop',
  reset: 'Reset',
  submit: 'Submit',
  evaluateInstantly: 'Evaluate instantly, without animating',
  backendReplayUnsupported: 'Backend replay not yet supported',
  programLocked: 'PROGRAM LOCKED',
  programLockedBody: 'Editing is locked during positioning, planning, or execution',
  eventLog: 'EVENT LOG',
  events: 'EVENTS',
  waitingEvents: 'Waiting for simulation events…',
  closeEventLog: 'Close event log',
  targetPreview: 'Target Hairstyle Preview',
  on: 'ON',
  off: 'OFF',
  cutterGrid: 'CUTTER GRID',
  worldAxes: 'WORLD AXES',
  gridPlannedPath: 'Grid and planned path',
  axes: 'Axes',
  current: 'Current',
  next: 'Next',
  progress: 'Progress',
  pathState: 'Path state',
  branch: 'Branch',
  search: 'Search',
  trajectory: 'Trajectory',
  planner: 'Planner',
  motion: 'Motion',
  expectedCuts: 'Expected cuts',
  speed: 'Speed',
  notPlanned: 'Not planned',
  connectedProgram: 'Connected for this program',
  staticIkOnly: 'Static IK map only',
  servoAngles: 'SERVO ANGLES',
  liveDegrees: 'LIVE · DEG',
  modelState: 'MODEL STATE',
  simulationOnly: 'SIMULATION ONLY',
  endEffector: 'END EFFECTOR',
  runMetrics: 'RUN METRICS',
  live: 'LIVE',
  currentVoxels: 'Current Voxels',
  targetVoxels: 'Target Voxels',
  sourceBlocks: 'Source Blocks',
  executedCommands: 'Executed Commands',
  estimatedDuration: 'Estimated Duration',
  scoreBreakdown: 'SCORE BREAKDOWN',
  finalScore: 'FINAL SCORE',
  completion: 'Completion',
  programEfficiency: 'Program Efficiency',
  time: 'Time',
  scorePending: 'Official scores will appear here after the program completes normally.',
  scoreStopped: 'Stopped: current metrics are provisional; no official score was generated.',
  baseYaw: 'Base Yaw',
  shoulder: 'Shoulder',
  elbow: 'Elbow',
  wrist: 'Wrist',
  cutterParked: 'Cutter · parked',
  tutorials: 'TUTORIALS',
  tutorialPickerTitle: 'Choose how to control the arm',
  tutorialPickerBody: 'Start with Cutter Grid, use Grid → Servo Angles to see how spatial intent becomes joint control, then learn direct angles in depth.',
  gridTutorial: 'Cutter Grid tutorial',
  gridTutorialBody: 'Build and test a certified five-block cut using fixed 3D axes.',
  controlModesTutorial: 'Grid → Servo Angles',
  controlModesTutorialBody: 'Compare spatial paths with joint commands on the same live workbench.',
  servoTutorial: 'Servo Angles tutorial',
  servoTutorialBody: 'Learn absolute angles, collision stops, Test, and Repeat.',
  stepsUnit: 'steps',
  lessonsHeading: 'LESSONS',
  lessonPickerTitle: 'Learn to drive the arm',
  lessonPickerBody: 'Start with Cutter Grid, then control each servo directly with Servo Angles. Pass the quiz and Blockly practical to unlock each next lesson.',
  gridLessonsTitle: 'Control the cutter in 3D space',
  gridLessonsBody: 'Learn fixed axes, distance, safe route planning, and a certified haircut. Each lesson ends with a quiz and Blockly practical.',
  servoLessonsTitle: 'Control each servo yourself',
  servoLessonsBody: 'Learn direct servo control and reach through verified targets. Each lesson ends with a quiz and Blockly practical.',
  sectionsUnit: 'sections',
  blockUnit: 'block',
  blocksUnit: 'blocks',
  lesson: 'Lesson',
  section: 'Section',
  previous: 'Previous',
  nextSection: 'Next section',
  nextLesson: 'Next lesson',
  backToLessons: 'Back to lessons',
  finish: 'Finish',
  nextAction: 'Next',
  skipStep: 'Skip step',
  done: 'Done',
  waitingForYou: 'Waiting for you',
  solved: 'Solved',
  pressTest: 'Press Test',
  read: 'READ',
  predict: 'PREDICT',
  build: 'BUILD',
  observe: 'OBSERVE',
  lessonChallenge: 'CHALLENGE',
  recap: 'RECAP',
  servoLessonBadge: 'SERVO ANGLES LESSON',
  gridLessonBadge: 'CUTTER GRID LESSON',
  perfectLesson: '100 out of 100. You cut exactly the requested hair and nothing else.',
  requiredAssessments: 'Quiz + Blockly practical',
  lockedLesson: 'Locked',
  checkAnswer: 'Check answer',
  quizPassed: 'Quiz passed',
  tryAgainNoAnswer: 'Not quite. Review the lesson and try again.',
  practicalRequired: 'Complete this task in Blockly and press Test.',
  practicalPassed: 'Blockly practical passed',
  practicalNotPassed: 'Test complete. The program does not meet the practical requirements yet.',
  practice: 'PRACTICE',
  practiceComplete: 'PRACTICE COMPLETE',
  practiceFailed: 'Practice could not continue',
  choosingChallenge: 'Choosing your next challenge…',
  ability: 'ABILITY',
  choosingNext: 'Choosing your next challenge…',
  versusRound: 'VERSUS ROUND',
  versusTitle: 'Same challenge. Same clock.',
  versusIntro: 'Everyone receives the same hairstyle at the same moment and has a fixed submission window. Closest to the target wins. Scores remain hidden until the round closes.',
  offlinePracticeTitle: 'Offline practice',
  backendOnlineTitle: 'Connected to a backend',
  offlinePracticeBody: 'No server is configured. Rounds stay in this tab, scripted bots act as opponents, and your browser calculates the scores. Set VITE_HCR_API_BASE_URL to connect to real opponents.',
  onlineRoundBody: 'The server replays and scores each program. Its clock decides whether a submission arrived before the deadline.',
  practiceBots: 'Three practice bots will join the room.',
  offlineRoomOnly: 'Offline rooms exist only in this tab, so their codes cannot be shared.',
  roundError: 'ROUND ERROR',
  dismissError: 'Dismiss error message',
  challengeForRound: 'Challenge for this round',
  multiplayerPrivacy: 'Multiplayer shares only your current UTC offset to show local time. It does not send a precise time-zone name or location.',
  hostRound: 'Host a round',
  hostRoundBody: 'Open a room, share the code, and start when everyone has joined.',
  roundLength: 'Round length',
  serverChoose: 'Let the server choose',
  openRoom: 'Open Room',
  joinRound: 'Join a round',
  joinRoundBody: 'Enter the code provided by the host.',
  roomCode: 'ROOM CODE',
  roomCodeLabel: 'Room code',
  joinRoom: 'Join Room',
  lobby: 'LOBBY',
  waitingStart: 'Waiting to start',
  leave: 'Leave',
  players: 'Players',
  you: 'YOU',
  bot: 'BOT',
  rules: 'Rules',
  startRound: 'Start Round',
  scoresSealed: 'Scores are sealed until the round closes',
  roundClosed: 'ROUND CLOSED',
  youWin: 'You win',
  noEntries: 'No entries',
  playAgain: 'Play Again',
  roundCancelled: 'ROUND CANCELLED',
  roundAbandoned: 'The round was abandoned',
  roundStarting: 'ROUND STARTING',
  revealingChallenge: 'Revealing the challenge…',
  simultaneousReveal: 'Everyone receives it at the same instant.',
  go: 'GO',
  closestWins: 'Closest to the target wins',
  loading: 'Loading',
  positioning: 'Positioning',
  planning: 'Planning',
  idle: 'Idle',
  running: 'Running',
  paused: 'Paused',
  completed: 'Completed',
  stopped: 'Stopped',
  error: 'Error',
  safeIkKnown: 'Safe IK known',
  noSafeIk: 'No safe IK found',
  executed: 'Executed',
  planned: 'Planned',
  serverClockRule: 'minutes, on the server clock',
  serverClockBody: 'A submission counts if the server receives it before the deadline. Your own clock is never consulted.',
  hiddenStandings: 'Standings stay hidden',
  hiddenStandingsBody: 'Nobody learns their rank until the round closes. You may test your own program, but every official score remains sealed.',
  bestAttempt: 'Resubmit freely; the best attempt counts',
  serverReplayBody: 'The server replays every program it scores, so the score comes from the program, not a browser-reported value.',
  localScoreBody: 'This is a practice round: this browser computes the scores, so the result is not official.',
  namesUnverified: 'Names are not verified',
  namesUnverifiedBody: 'There are no accounts here. Anyone can choose any name, so standings do not verify identity.',
  lobbyStartHint: 'Anyone in the room can start. The challenge is revealed to everyone at the same instant. Local clocks use only a shared UTC offset; no precise time-zone name or location is sent.',
  closed: 'CLOSED',
  timeLeft: 'TIME LEFT',
  attemptLocked: 'Attempt locked in. Submit again to improve it; your best attempt counts.',
  attemptRejected: 'That attempt was not accepted.',
  roundResults: 'Round results',
  finalScoreMetric: 'Final score',
  similarityMetric: 'Similarity to target',
  rankedBy: 'Ranked by',
  noAttempt: 'no attempt',
} as const;

const MESSAGES: Record<AppLocale, Partial<Record<MessageKey, string>>> = {
  en: EN_MESSAGES,
  'zh-CN': {
    language: '语言', player: '玩家', tagline: '编程控制机械臂，修剪发型，挑战时间。',
    tutorial: '教程', tutorialBody: '学习网格路径、舵机角度，以及两种控制方式如何衔接。', learn: '开始学习 →',
    lessons: '课程', lessonsBody: '十节 Cutter Grid 与八节舵机角度课程，每课均有必答选择题和 Blockly 实操。', practise: '开始练习 →',
    solo: '单人练习', soloBody: '完成一题后，系统会根据表现选择下一题。', start: '开始 →',
    versus: '多人对战', versusBody: '相同发型、相同计时，最接近目标者获胜。', play: '进入 →',
    backendConnected: '后端已连接', offlinePractice: '离线 · 练习',
    defaultChallengeName: '顶部修剪', defaultChallengeDescription: '只移除头顶高亮的 11 个体素，其他头发保持不动。五个硬件舵机都从 90° 开始。将 X · 底座偏航从 90° 移到 150°；Y、Z、B、E 保持在 Home 位置。课程会把这次扫掠拆成更小的步骤。',
    requiredData: '在线评分必须将编译后的 Blockly 程序、关卡和分数数据发送至服务器，以便重放并评分。',
    researchChoice: '允许将我提交的程序、分数、主语言和粗粒度 UTC 偏移用于去标识化学习研究。',
    researchHint: '可在“更多设置”中分别关闭主语言或 UTC 偏移；不会收集浏览器指纹或精确时区名称。',
    dataSettings: '数据设置', privacyTitle: '选择如何使用你的数据',
    privacyIntro: '模拟器需要部分数据完成在线评分；去标识化研究用途是独立选择。',
    necessaryTitle: '必要评分数据', necessaryBody: '编译后的 Blockly 程序、关卡版本和分数。在线练习及对战必须开启。',
    optionalTitle: '可选学习研究', optionalBody: '提交的程序与分数，以及主语言和粗粒度 UTC 偏移；不收集浏览器指纹或精确时区名称。',
    necessaryOnly: '仅必要数据', acceptResearch: '同意参与研究', moreSettings: '更多设置', saveSettings: '保存设置',
    notNow: '暂不参与', allowAllResearch: '同意全部研究选项', programResearchTitle: '程序与成绩', programResearchBody: '允许提交的 Blockly IR 和评分结果进入去标识化研究数据集。',
    languageResearchTitle: '主语言', languageResearchBody: '只共享 zh、en 等粗粒度主语言代码。', timezoneResearchTitle: 'UTC 偏移', timezoneResearchBody: '只共享当前分钟偏移，不共享精确时区名称。', neverCollected: '永远不会收集浏览器指纹。',
    participateStudy: '参与学术研究并进入', exitStudy: '退出', studyTitle: '参与学术研究', studyIntro: 'HCR 是一项研究人们如何学习机械臂编程的学术项目。请阅读下方数据说明，然后主动选择是否参与。',
    studyDeclinedTitle: '你已选择不参与研究', studyDeclinedBody: '系统尚未创建模拟器会话或玩家标识。你可以关闭此页面，或重新查看研究说明。', reviewStudy: '重新查看研究说明', closeApplication: '关闭应用',
    menu: '菜单', back: '返回', backToMenu: '返回菜单', challenge: '挑战', program: '程序', programPanel: 'Blockly 程序面板', programIr: '程序 IR', blocks: '积木块', inspector: '检查器', simulationStatus: '仿真状态', cameraOrbit: '相机 / 环绕视角', local: '本地', programError: '程序错误', retry: '重试', webglUnsupported: '当前浏览器不支持 WebGL。请使用最新版 Chrome 或 Edge。',
    collapseProgram: '收起程序面板', expandProgram: '展开程序面板', collapseInspector: '收起状态面板', expandInspector: '展开状态面板', programmingMode: '编程模式', servoAnglesMode: '舵机角度', cutterGridMode: '切刀网格', servoAnglesProgram: '舵机角度程序', cutterGridProgram: '切刀网格程序', simulationControls: '仿真控制',
    test: '测试', run: '运行', resume: '继续', pause: '暂停', step: '单步', stop: '停止', reset: '重置', submit: '提交', evaluateInstantly: '立即评估，不播放动画', backendReplayUnsupported: '后端暂不支持重放',
    programLocked: '程序已锁定', programLockedBody: '定位、规划或执行期间无法编辑', eventLog: '事件日志', events: '条事件', waitingEvents: '等待仿真事件…', closeEventLog: '关闭事件日志',
    targetPreview: '目标发型预览', on: '开', off: '关', cutterGrid: '切刀网格', worldAxes: '世界坐标轴', gridPlannedPath: '网格与规划路径', axes: '坐标轴', current: '当前位置', next: '下一位置', progress: '进度', pathState: '路径状态', branch: '分支', search: '搜索', trajectory: '轨迹', planner: '规划器', motion: '运动', expectedCuts: '预计切除', speed: '速度', notPlanned: '尚未规划', connectedProgram: '当前程序路径已连通', staticIkOnly: '仅静态逆运动学图',
    servoAngles: '舵机角度', liveDegrees: '实时 · 度', modelState: '模型状态', simulationOnly: '仅用于仿真', endEffector: '末端执行器', runMetrics: '运行指标', live: '实时', currentVoxels: '当前体素', targetVoxels: '目标体素', sourceBlocks: '源积木块', executedCommands: '已执行命令', estimatedDuration: '预计时长', scoreBreakdown: '评分明细', finalScore: '最终得分', completion: '完成度', programEfficiency: '程序效率', time: '时间', scorePending: '程序正常完成后将在此显示正式得分。', scoreStopped: '已停止：当前指标仅供参考，未生成正式得分。',
    baseYaw: '底座偏航', shoulder: '肩部', elbow: '肘部', wrist: '腕部', cutterParked: '切刀 · 停放',
    tutorials: '教程', tutorialPickerTitle: '选择机械臂控制方式', tutorialPickerBody: '先学习 Cutter Grid，再通过“Grid → 舵机角度”理解空间意图如何转换为关节控制，最后深入学习直接角度控制。', gridTutorial: 'Cutter Grid 教程', gridTutorialBody: '使用固定三维坐标轴，构建并测试一条经过认证的五积木块切割路径。', controlModesTutorial: 'Grid → 舵机角度', controlModesTutorialBody: '在同一个实时工作台中比较空间路径与关节命令。', servoTutorial: '舵机角度教程', servoTutorialBody: '学习绝对角度、碰撞停止、测试与重复。', stepsUnit: '步',
    lessonsHeading: '课程', lessonPickerTitle: '学习控制机械臂', lessonPickerBody: '先学习 Cutter Grid，再直接控制舵机角度。完成每课的选择题和 Blockly 实操后，下一课才会解锁。', gridLessonsTitle: '在三维空间控制切刀', gridLessonsBody: '从固定坐标轴和距离，逐步学习安全路径规划与经验证的完整理发路径；每课均有选择题和 Blockly 实操。', servoLessonsTitle: '直接控制每个舵机', servoLessonsBody: '通过经验证的目标学习舵机控制与可达范围；每课均有选择题和 Blockly 实操。', sectionsUnit: '个部分', blockUnit: '个积木块', blocksUnit: '个积木块',
    lesson: '第', section: '部分', previous: '上一部分', nextSection: '下一部分', nextLesson: '下一课', backToLessons: '返回课程', finish: '完成', nextAction: '下一步', skipStep: '跳过此步', done: '已完成', waitingForYou: '等待操作', solved: '已解决', pressTest: '请按“测试”', read: '阅读', predict: '预测', build: '搭建', observe: '观察', lessonChallenge: '挑战', recap: '回顾', servoLessonBadge: '舵机角度课程', gridLessonBadge: 'Cutter Grid 课程', perfectLesson: '100 / 100：只切除目标头发，没有误切。', requiredAssessments: '选择题 + Blockly 实操', lockedLesson: '未解锁', checkAnswer: '检查答案', quizPassed: '选择题已通过', tryAgainNoAnswer: '还不正确。请回顾课程后重试。', practicalRequired: '请在 Blockly 中完成任务，然后按“测试”。', practicalPassed: 'Blockly 实操已通过', practicalNotPassed: '测试已完成，但程序尚未满足本节实操要求。',
    practice: '练习', practiceComplete: '练习完成', practiceFailed: '无法继续练习', choosingChallenge: '正在选择下一项挑战…', ability: '能力估计', choosingNext: '正在选择下一项挑战…',
    versusRound: '多人对战', versusTitle: '相同挑战，相同计时。', versusIntro: '所有玩家会在同一时刻收到相同发型，并在固定时间内提交。最接近目标者获胜；本轮结束前不显示分数。', offlinePracticeTitle: '离线练习', backendOnlineTitle: '已连接后端', offlinePracticeBody: '当前未配置服务器。对战只在此标签页中运行，对手是预设机器人，分数由浏览器计算。设置 VITE_HCR_API_BASE_URL 后可连接真实对手。', onlineRoundBody: '服务器会重放并评分每个程序，并以服务器时间判断提交是否赶上截止时间。', practiceBots: '三个练习机器人会加入房间。', offlineRoomOnly: '离线房间只存在于此标签页，房间码无法分享。', roundError: '对战错误', dismissError: '关闭错误消息', challengeForRound: '本轮挑战', multiplayerPrivacy: '多人游戏仅共享当前 UTC 偏移，用于显示玩家当地时间；不会发送精确时区名称或位置。', hostRound: '创建对战', hostRoundBody: '创建房间、分享房间码，所有人进入后即可开始。', roundLength: '对战时长', serverChoose: '由服务器选择', openRoom: '创建房间', joinRound: '加入对战', joinRoundBody: '输入房主提供的房间码。', roomCode: '房间码', roomCodeLabel: '房间码', joinRoom: '加入房间', lobby: '等候室', waitingStart: '等待开始', leave: '离开', players: '玩家', you: '你', bot: '机器人', rules: '规则', startRound: '开始对战', scoresSealed: '本轮结束前所有分数均保密', roundClosed: '本轮结束', youWin: '你获胜', noEntries: '无人提交', playAgain: '再玩一次', roundCancelled: '对战已取消', roundAbandoned: '本轮对战已放弃', roundStarting: '对战即将开始', revealingChallenge: '正在公布挑战…', simultaneousReveal: '所有玩家会在同一时刻收到挑战。', go: '开始', closestWins: '最接近目标者获胜', loading: '正在载入', positioning: '正在定位', planning: '正在规划', idle: '待机', running: '正在运行', paused: '已暂停', completed: '已完成', stopped: '已停止', error: '错误', safeIkKnown: '已知安全逆解', noSafeIk: '未找到安全逆解', executed: '已执行', planned: '已规划', serverClockRule: '分钟，以服务器时钟为准', serverClockBody: '服务器在截止时间前收到提交即为有效；不会参考你的设备时钟。', hiddenStandings: '排名暂不公开', hiddenStandingsBody: '本轮结束前无人知道自己的排名。你可以测试自己的程序，但所有正式分数均保持保密。', bestAttempt: '可重复提交，以最佳一次为准', serverReplayBody: '服务器会重放每个评分程序，因此分数来自程序本身，而不是浏览器上报的数值。', localScoreBody: '这是练习对战：分数由当前浏览器计算，因此结果不是正式成绩。', namesUnverified: '显示名称未经验证', namesUnverifiedBody: '这里没有账户系统，任何人都可选择任意名称，因此排名不能用于验证身份。', lobbyStartHint: '房间内任何人都可开始。挑战会同时向所有玩家公布。当地时间仅使用共享的 UTC 偏移；不会发送精确时区名称或位置。', closed: '已结束', timeLeft: '剩余时间', attemptLocked: '提交已确认。可以再次提交改进，以最佳一次为准。', attemptRejected: '本次提交未被接受。', roundResults: '对战结果', finalScoreMetric: '最终得分', similarityMetric: '与目标的相似度', rankedBy: '排名依据', noAttempt: '未提交',
  },
  'zh-TW': {
    language: '語言', player: '玩家', tagline: '編程控制機械臂、修剪髮型、挑戰時間。',
    tutorial: '教學', tutorialBody: '學習網格路徑、伺服角度，以及兩種控制方式如何銜接。', learn: '開始學習 →',
    lessons: '課程', lessonsBody: '十節 Cutter Grid 與八節伺服角度課程，每課均有必答選擇題和 Blockly 實作。', practise: '開始練習 →',
    solo: '單人練習', soloBody: '完成一題後，系統會依表現選擇下一題。', start: '開始 →',
    versus: '多人對戰', versusBody: '相同髮型、相同計時，最接近目標者獲勝。', play: '進入 →',
    backendConnected: '後端已連線', offlinePractice: '離線 · 練習',
    defaultChallengeName: '頂部修剪', defaultChallengeDescription: '只移除頭頂標示的 11 個體素，其餘頭髮保持不動。五個硬體舵機都從 90° 開始。將 X · 底座偏航從 90° 移到 150°；Y、Z、B、E 保持在 Home 位置。課程會把這次掃掠拆成較小的步驟。',
    servoAnglesMode: '伺服角度', cutterGridMode: '切刀網格', servoAnglesProgram: '伺服角度程式', cutterGridProgram: '切刀網格程式',
    offlinePracticeBody: '目前未設定伺服器。對戰只會在此分頁執行，對手是預設機器人，分數由瀏覽器計算。設定 VITE_HCR_API_BASE_URL 後即可連接真人對手。', onlineRoundBody: '伺服器會重播並評分每個程式，並以伺服器時間判斷提交是否趕上截止時間。', practiceBots: '三個練習機器人會加入房間。', offlineRoomOnly: '離線房間只存在於此分頁，房間碼無法分享。', roundError: '對戰錯誤', dismissError: '關閉錯誤訊息', challengeForRound: '本輪挑戰',
    requiredData: '線上評分必須把編譯後的 Blockly 程式、關卡及分數資料傳送至伺服器，以便重播及評分。',
    researchChoice: '允許將我提交的程式、分數、主要語言和粗略 UTC 偏移用於去識別化學習研究。',
    researchHint: '可在「更多設定」中分別關閉主要語言或 UTC 偏移；不會收集瀏覽器指紋或精確時區名稱。',
    dataSettings: '資料設定', privacyTitle: '選擇如何使用你的資料', privacyIntro: '模擬器需要部分資料完成線上評分；去識別化研究用途是獨立選擇。',
    necessaryTitle: '必要評分資料', necessaryBody: '編譯後的 Blockly 程式、關卡版本和分數。線上練習及對戰必須開啟。',
    optionalTitle: '選填學習研究', optionalBody: '提交的程式與分數，以及主要語言和粗略 UTC 偏移；不收集瀏覽器指紋或精確時區名稱。',
    necessaryOnly: '只用必要資料', acceptResearch: '同意參與研究', moreSettings: '更多設定', saveSettings: '儲存設定',
    notNow: '暫不參與', allowAllResearch: '同意全部研究選項', programResearchTitle: '程式與成績', programResearchBody: '允許提交的 Blockly IR 和評分結果進入去識別化研究資料集。',
    languageResearchTitle: '主要語言', languageResearchBody: '只分享 zh、en 等粗略主要語言代碼。', timezoneResearchTitle: 'UTC 偏移', timezoneResearchBody: '只分享目前分鐘偏移，不分享精確時區名稱。', neverCollected: '永遠不會收集瀏覽器指紋。',
    participateStudy: '參與學術研究並進入', exitStudy: '退出', studyTitle: '參與學術研究', studyIntro: 'HCR 是一項研究人們如何學習機械臂編程的學術計畫。請閱讀下方資料說明，再主動選擇是否參與。',
    studyDeclinedTitle: '你已選擇不參與研究', studyDeclinedBody: '系統尚未建立模擬器工作階段或玩家識別碼。你可以關閉此頁面，或重新查看研究說明。', reviewStudy: '重新查看研究說明', closeApplication: '關閉應用程式',
    menu: '選單', back: '返回', backToMenu: '返回選單', challenge: '挑戰', program: '程式', programPanel: 'Blockly 程式面板', programIr: '程式 IR', blocks: '積木塊', inspector: '檢查器', simulationStatus: '模擬狀態', cameraOrbit: '相機 / 環繞視角', local: '本機', programError: '程式錯誤', retry: '重試', webglUnsupported: '目前瀏覽器不支援 WebGL。請使用最新版 Chrome 或 Edge。',
    collapseProgram: '收合程式面板', expandProgram: '展開程式面板', collapseInspector: '收合狀態面板', expandInspector: '展開狀態面板', programmingMode: '編程模式', simulationControls: '模擬控制',
    test: '測試', run: '執行', resume: '繼續', pause: '暫停', step: '單步執行', stop: '停止', reset: '重設', submit: '提交', evaluateInstantly: '立即評估，不播放動畫', backendReplayUnsupported: '後端目前不支援重播',
    programLocked: '程式已鎖定', programLockedBody: '定位、規劃或執行期間無法編輯', eventLog: '事件記錄', events: '筆事件', waitingEvents: '正在等待模擬事件…', closeEventLog: '關閉事件記錄',
    targetPreview: '目標髮型預覽', on: '開', off: '關', cutterGrid: '切刀網格', worldAxes: '世界座標軸', gridPlannedPath: '網格與規劃路徑', axes: '座標軸', current: '目前位置', next: '下一位置', progress: '進度', pathState: '路徑狀態', branch: '分支', search: '搜尋', trajectory: '軌跡', planner: '規劃器', motion: '運動', expectedCuts: '預計切除', speed: '速度', notPlanned: '尚未規劃', connectedProgram: '目前程式路徑已連通', staticIkOnly: '僅靜態逆向運動學圖',
    servoAngles: '伺服角度', liveDegrees: '即時 · 度', modelState: '模型狀態', simulationOnly: '僅用於模擬', endEffector: '末端執行器', runMetrics: '執行指標', live: '即時', currentVoxels: '目前體素', targetVoxels: '目標體素', sourceBlocks: '來源積木塊', executedCommands: '已執行指令', estimatedDuration: '預估時間', scoreBreakdown: '評分明細', finalScore: '最終分數', completion: '完成度', programEfficiency: '程式效率', time: '時間', scorePending: '程式正常完成後將在此顯示正式分數。', scoreStopped: '已停止：目前指標僅供參考，未產生正式分數。',
    baseYaw: '底座偏航', shoulder: '肩部', elbow: '肘部', wrist: '腕部', cutterParked: '切刀 · 停放',
    tutorials: '教學', tutorialPickerTitle: '選擇機械臂控制方式', tutorialPickerBody: '先學習 Cutter Grid，再透過「Grid → 伺服角度」理解空間意圖如何轉換為關節控制，最後深入學習直接角度控制。', gridTutorial: 'Cutter Grid 教學', gridTutorialBody: '使用固定三維座標軸，建立並測試一條經過認證的五積木塊切割路徑。', controlModesTutorial: 'Grid → 伺服角度', controlModesTutorialBody: '在同一個即時工作台中比較空間路徑與關節指令。', servoTutorial: '伺服角度教學', servoTutorialBody: '學習絕對角度、碰撞停止、測試與重複。', stepsUnit: '步',
    lessonsHeading: '課程', lessonPickerTitle: '學習控制機械臂', lessonPickerBody: '先學習 Cutter Grid，再直接控制伺服角度。完成每課的選擇題和 Blockly 實作後，下一課才會解鎖。', gridLessonsTitle: '在三維空間控制切刀', gridLessonsBody: '從固定座標軸和距離，逐步學習安全路徑規劃與經驗證的完整理髮路徑；每課均有選擇題和 Blockly 實作。', servoLessonsTitle: '直接控制每個伺服馬達', servoLessonsBody: '透過經驗證的目標學習伺服控制與可達範圍；每課均有選擇題和 Blockly 實作。', sectionsUnit: '個部分', blockUnit: '個積木塊', blocksUnit: '個積木塊',
    lesson: '第', section: '部分', previous: '上一部分', nextSection: '下一部分', nextLesson: '下一課', backToLessons: '返回課程', finish: '完成', nextAction: '下一步', skipStep: '略過此步', done: '已完成', waitingForYou: '等待操作', solved: '已解決', pressTest: '請按「測試」', read: '閱讀', predict: '預測', build: '建立', observe: '觀察', lessonChallenge: '挑戰', recap: '回顧', servoLessonBadge: '伺服角度課程', gridLessonBadge: 'Cutter Grid 課程', perfectLesson: '100 / 100：只切除目標頭髮，沒有誤切。', requiredAssessments: '選擇題 + Blockly 實作', lockedLesson: '尚未解鎖', checkAnswer: '檢查答案', quizPassed: '選擇題已通過', tryAgainNoAnswer: '還不正確。請回顧課程後再試。', practicalRequired: '請在 Blockly 中完成任務，然後按「測試」。', practicalPassed: 'Blockly 實作已通過', practicalNotPassed: '測試已完成，但程式尚未符合本節實作要求。',
    practice: '練習', practiceComplete: '練習完成', practiceFailed: '無法繼續練習', choosingChallenge: '正在選擇下一項挑戰…', ability: '能力估計', choosingNext: '正在選擇下一項挑戰…',
    versusRound: '多人對戰', versusTitle: '相同挑戰，相同計時。', versusIntro: '所有玩家會在同一時刻收到相同髮型，並在固定時間內提交。最接近目標者獲勝；本輪結束前不顯示分數。', offlinePracticeTitle: '離線練習', backendOnlineTitle: '已連接後端', multiplayerPrivacy: '多人遊戲只會分享目前 UTC 偏移，用於顯示玩家當地時間；不會傳送精確時區名稱或位置。', hostRound: '建立對戰', hostRoundBody: '建立房間、分享房間碼，所有人進入後即可開始。', roundLength: '對戰時間', serverChoose: '由伺服器選擇', openRoom: '建立房間', joinRound: '加入對戰', joinRoundBody: '輸入房主提供的房間碼。', roomCode: '房間碼', roomCodeLabel: '房間碼', joinRoom: '加入房間', lobby: '等候室', waitingStart: '等待開始', leave: '離開', players: '玩家', you: '你', bot: '機器人', rules: '規則', startRound: '開始對戰', scoresSealed: '本輪結束前所有分數均保密', roundClosed: '本輪結束', youWin: '你獲勝', noEntries: '無人提交', playAgain: '再玩一次', roundCancelled: '對戰已取消', roundAbandoned: '本輪對戰已放棄', roundStarting: '對戰即將開始', revealingChallenge: '正在公布挑戰…', simultaneousReveal: '所有玩家會在同一時刻收到挑戰。', go: '開始', closestWins: '最接近目標者獲勝', loading: '正在載入', positioning: '正在定位', planning: '正在規劃', idle: '待機', running: '正在執行', paused: '已暫停', completed: '已完成', stopped: '已停止', error: '錯誤', safeIkKnown: '已知安全逆解', noSafeIk: '未找到安全逆解', executed: '已執行', planned: '已規劃', serverClockRule: '分鐘，以伺服器時鐘為準', serverClockBody: '伺服器在截止時間前收到提交即為有效；不會參考你的裝置時鐘。', hiddenStandings: '排名暫不公開', hiddenStandingsBody: '本輪結束前沒有人知道自己的排名。你可以測試自己的程式，但所有正式分數均保持保密。', bestAttempt: '可重複提交，以最佳一次為準', serverReplayBody: '伺服器會重播每個評分程式，因此分數來自程式本身，而不是瀏覽器回報的數值。', localScoreBody: '這是練習對戰：分數由目前瀏覽器計算，因此結果不是正式成績。', namesUnverified: '顯示名稱未經驗證', namesUnverifiedBody: '這裡沒有帳號系統，任何人都可選擇任意名稱，因此排名不能用來驗證身分。', lobbyStartHint: '房間內任何人都可開始。挑戰會同時向所有玩家公布。當地時間只使用共享的 UTC 偏移；不會傳送精確時區名稱或位置。', closed: '已結束', timeLeft: '剩餘時間', attemptLocked: '提交已確認。可以再次提交改進，以最佳一次為準。', attemptRejected: '本次提交未被接受。', roundResults: '對戰結果', finalScoreMetric: '最終分數', similarityMetric: '與目標的相似度', rankedBy: '排名依據', noAttempt: '未提交',
  },
  'zh-HK': {
    language: '語言', player: '玩家', tagline: '編程控制機械臂、剪出髮型、挑戰時間。',
    tutorial: '教學', tutorialBody: '學識網格路徑、舵機角度，同埋兩種控制方式點樣配合。', learn: '開始學 →',
    lessons: '課堂', lessonsBody: '十課 Cutter Grid 同八課舵機角度，每課都有必答選擇題同 Blockly 實作。', practise: '開始練習 →',
    solo: '單人練習', soloBody: '完成一題之後，系統會按你嘅表現揀下一題。', start: '開始 →',
    versus: '多人對戰', versusBody: '同一髮型、同一計時，最接近目標嘅玩家勝出。', play: '入場 →',
    backendConnected: '後端已連線', offlinePractice: '離線 · 練習',
    defaultChallengeName: '頭頂修剪', defaultChallengeDescription: '只剪走頭頂標示咗嘅 11 個體素，其他頭髮唔好郁。五個硬件舵機都由 90° 開始。將 X · 底座偏航由 90° 移到 150°；Y、Z、B、E 保持喺 Home 位置。課堂會將呢次掃掠拆成幾個較細步驟。',
    servoAnglesMode: '舵機角度', cutterGridMode: '切刀網格', servoAnglesProgram: '舵機角度程式', cutterGridProgram: '切刀網格程式',
    tutorials: '教學', tutorialPickerTitle: '揀選機械臂控制方式', tutorialPickerBody: '先學 Cutter Grid，再用「Grid → 舵機角度」了解空間路徑點樣變成關節命令，最後深入學直接角度控制。', gridTutorial: 'Cutter Grid 教學', gridTutorialBody: '用固定三維座標軸，建立同測試一條經認證嘅五積木塊切割路徑。', controlModesTutorial: 'Grid → 舵機角度', controlModesTutorialBody: '喺同一個即時工作台比較空間路徑同關節命令。', servoTutorial: '舵機角度教學', servoTutorialBody: '學習絕對角度、碰撞停止、測試同重複。', stepsUnit: '步',
    lessonsHeading: '課堂', lessonPickerTitle: '學習控制機械臂', lessonPickerBody: '先學 Cutter Grid，再直接控制舵機角度。完成每課嘅選擇題同 Blockly 實作之後，下一課先會解鎖。', gridLessonsTitle: '喺三維空間控制切刀', gridLessonsBody: '由固定座標軸同距離開始，逐步學習安全路徑規劃同經驗證嘅完整理髮路徑；每課都有選擇題同 Blockly 實作。', servoLessonsTitle: '直接控制每個舵機', servoLessonsBody: '透過經驗證嘅目標學習舵機控制同可達範圍；每課都有選擇題同 Blockly 實作。',
    lesson: '第', section: '部分', previous: '上一部分', nextSection: '下一部分', nextLesson: '下一課', backToLessons: '返回課堂', finish: '完成', nextAction: '下一步', done: '完成', waitingForYou: '等緊你', solved: '已完成', pressTest: '請按「測試」', read: '閱讀', predict: '預測', build: '建立', observe: '觀察', lessonChallenge: '挑戰', recap: '回顧', servoLessonBadge: '舵機角度課堂', gridLessonBadge: 'Cutter Grid 課堂', perfectLesson: '100 / 100：只剪走目標頭髮，冇剪多。', requiredAssessments: '選擇題 + Blockly 實作', lockedLesson: '未解鎖', checkAnswer: '檢查答案', quizPassed: '選擇題已通過', tryAgainNoAnswer: '仲未正確。請重溫課堂內容再試。', practicalRequired: '請喺 Blockly 完成任務，然後按「測試」。', practicalPassed: 'Blockly 實作已通過', practicalNotPassed: '測試完成，但個程式仲未符合今節實作要求。',
    offlinePracticeBody: '而家未設定伺服器。對戰只會喺呢個分頁運行，對手係預設機械人，分數由瀏覽器計算。設定 VITE_HCR_API_BASE_URL 之後就可以連接真人對手。', onlineRoundBody: '伺服器會重播同評分每個程式，亦會用伺服器時間判斷提交有冇趕及截止時間。', practiceBots: '三個練習機械人會加入房間。', offlineRoomOnly: '離線房間只存在喺呢個分頁，房間碼唔可以分享。', roundError: '對戰錯誤', dismissError: '關閉錯誤訊息', challengeForRound: '今輪挑戰',
    requiredData: '網上評分一定要將編譯後嘅 Blockly 程式、關卡同分數資料傳送去伺服器，先可以重播同評分。',
    researchChoice: '同意將我提交嘅程式、分數、主要語言同粗略 UTC 偏移用作去識別化學習研究。',
    researchHint: '可以喺「更多設定」分別關閉主要語言或者 UTC 偏移；唔會收集瀏覽器指紋或精確時區名稱。',
    dataSettings: '資料設定', privacyTitle: '揀選點樣使用你嘅資料', privacyIntro: '模擬器要用部分資料先做到網上評分；去識別化研究係另一個獨立選擇。',
    necessaryTitle: '必要評分資料', necessaryBody: '編譯後嘅 Blockly 程式、關卡版本同分數。網上練習同對戰一定要開啟。',
    optionalTitle: '自願學習研究', optionalBody: '提交嘅程式同分數，加主要語言同粗略 UTC 偏移；唔收集瀏覽器指紋或精確時區名稱。',
    necessaryOnly: '只用必要資料', acceptResearch: '同意參與研究', moreSettings: '更多設定', saveSettings: '儲存設定',
    notNow: '暫時唔參與', allowAllResearch: '同意全部研究選項', programResearchTitle: '程式同成績', programResearchBody: '允許提交嘅 Blockly IR 同評分結果進入去識別化研究資料集。',
    languageResearchTitle: '主要語言', languageResearchBody: '只分享 zh、en 呢類粗略主要語言代碼。', timezoneResearchTitle: 'UTC 偏移', timezoneResearchBody: '只分享目前分鐘偏移，唔分享精確時區名稱。', neverCollected: '永遠唔會收集瀏覽器指紋。',
    participateStudy: '參與學術研究並進入', exitStudy: '退出', studyTitle: '參與學術研究', studyIntro: 'HCR 係一項研究人點樣學機械臂編程嘅學術項目。請睇清楚下面嘅資料說明，再主動揀參唔參與。',
    studyDeclinedTitle: '你已揀唔參與研究', studyDeclinedBody: '系統未建立模擬器工作階段或者玩家識別碼。你可以關閉呢一頁，或者再睇研究說明。', reviewStudy: '再睇研究說明', closeApplication: '關閉應用程式',
  },
  ja: {
    language: '言語', player: 'プレイヤー', tagline: 'アームをプログラムし、髪型を作り、時間に挑戦。',
    tutorial: 'チュートリアル', tutorialBody: 'グリッド経路、サーボ角度、2つの操作方法のつながりを学びます。', learn: '学ぶ →',
    lessons: 'レッスン', lessonsBody: 'Cutter Grid 10課とサーボ角度8課。各課に必須のクイズとBlockly実習があります。', practise: '練習 →',
    solo: '一人で練習', soloBody: '成績に応じて次の課題が選ばれます。', start: '開始 →',
    versus: '対戦', versusBody: '同じ髪型と制限時間で、目標に最も近い人が勝ちます。', play: '参加 →',
    backendConnected: 'バックエンド接続済み', offlinePractice: 'オフライン・練習',
    defaultChallengeName: '頭頂部を整える', defaultChallengeDescription: '頭頂部でハイライトされた11個のボクセルだけを取り除き、ほかの髪は残します。5基のハードウェアサーボはすべて90°から始まります。Y、Z、B、EをHomeのままにして、X · Base Yawを90°から150°へ動かしてください。レッスンでは、この動きを短い手順に分けて練習できます。',
    requiredData: 'オンライン採点には、コンパイル済みBlocklyプログラム、課題、得点データのサーバー送信が必要です。',
    researchChoice: '提出したプログラムと得点、主要言語、概略UTCオフセットを、個人を直接特定しない学習研究データとして利用することに同意します。',
    researchHint: '主要言語とUTCオフセットは「詳細設定」で個別に無効にできます。ブラウザー指紋や正確なタイムゾーン名は収集しません。',
    dataSettings: 'データ設定', privacyTitle: 'データの利用方法', privacyIntro: 'オンライン採点には一部のデータが必要です。研究への利用は別に選択できます。',
    necessaryTitle: '採点に必要なデータ', necessaryBody: 'コンパイル済みBlocklyプログラム、課題のバージョン、得点。オンライン練習と対戦では常に使用します。',
    optionalTitle: '学習研究への提供', optionalBody: '提出したプログラムと得点、主要言語、概略UTCオフセット。ブラウザー指紋や正確なタイムゾーン名は含みません。',
    necessaryOnly: '必要なデータのみ', acceptResearch: '研究に参加', moreSettings: '詳細設定', saveSettings: '設定を保存',
    notNow: '今回は参加しない', allowAllResearch: 'すべての研究項目を許可', programResearchTitle: 'プログラムと得点', programResearchBody: '提出したBlockly IRと採点結果を、個人を直接特定しない研究データセットに追加します。',
    languageResearchTitle: '主要言語', languageResearchBody: 'zhやenなど、主要言語の大まかなコードだけを共有します。', timezoneResearchTitle: 'UTCオフセット', timezoneResearchBody: '現在の分単位のオフセットだけを共有し、正確なタイムゾーン名は送りません。', neverCollected: 'ブラウザー指紋は収集しません。',
    participateStudy: '学術研究に参加する', exitStudy: '終了', studyTitle: '学術研究への参加', studyIntro: 'HCRは、ロボットプログラミングの学習過程を調べる学術研究です。データの扱いを確認し、参加するかどうかを選んでください。',
    studyDeclinedTitle: '研究には参加しません', studyDeclinedBody: 'シミュレーターのセッションやプレイヤーIDは作成されていません。このページを閉じるか、研究内容をもう一度確認できます。', reviewStudy: '研究内容を確認する', closeApplication: 'アプリを閉じる',
  },
  ko: {
    language: '언어', player: '플레이어', tagline: '로봇 팔을 프로그래밍하고 머리를 다듬어 기록에 도전하세요.',
    tutorial: '튜토리얼', tutorialBody: '그리드 경로, 서보 각도와 두 제어 방식의 연결을 배웁니다.', learn: '학습 →',
    lessons: '레슨', lessonsBody: 'Cutter Grid 10개와 서보 각도 8개 레슨에는 필수 퀴즈와 Blockly 실습이 있습니다.', practise: '연습 →',
    solo: '혼자 연습', soloBody: '성과에 따라 다음 도전이 선택됩니다.', start: '시작 →',
    versus: '멀티플레이', versusBody: '같은 헤어스타일과 시간으로 목표에 가장 가까운 사람이 승리합니다.', play: '입장 →',
    backendConnected: '백엔드 연결됨', offlinePractice: '오프라인 · 연습',
    defaultChallengeName: '정수리 다듬기', defaultChallengeDescription: '정수리에 표시된 복셀 11개만 제거하고 나머지 머리카락은 그대로 두세요. 하드웨어 서보 5개는 모두 90°에서 시작합니다. Y, Z, B, E는 Home에 둔 채 X · Base Yaw를 90°에서 150°로 움직이세요. 레슨에서 이 동작을 짧은 단계로 나누어 연습할 수 있습니다.',
    requiredData: '온라인 채점에는 컴파일된 Blockly 프로그램, 도전 및 점수 데이터를 서버로 보내야 합니다.',
    researchChoice: '제출한 프로그램과 점수, 기본 언어, 대략적인 UTC 오프셋을 비식별화된 학습 연구 데이터로 사용하는 데 동의합니다.',
    researchHint: '기본 언어와 UTC 오프셋은 ‘세부 설정’에서 각각 끌 수 있습니다. 브라우저 지문이나 정확한 시간대 이름은 수집하지 않습니다.',
    dataSettings: '데이터 설정', privacyTitle: '데이터 사용 선택', privacyIntro: '온라인 채점에는 일부 데이터가 필요합니다. 연구 활용 여부는 별도로 선택할 수 있습니다.',
    necessaryTitle: '채점에 필요한 데이터', necessaryBody: '컴파일된 Blockly 프로그램, 도전 버전, 점수입니다. 온라인 연습과 대전에서는 항상 사용합니다.',
    optionalTitle: '학습 연구 참여', optionalBody: '제출한 프로그램과 점수, 기본 언어, 대략적인 UTC 오프셋입니다. 브라우저 지문과 정확한 시간대 이름은 포함하지 않습니다.',
    necessaryOnly: '필수 데이터만', acceptResearch: '연구 참여', moreSettings: '세부 설정', saveSettings: '설정 저장',
    notNow: '참여하지 않음', allowAllResearch: '모든 연구 항목 허용', programResearchTitle: '프로그램과 점수', programResearchBody: '제출한 Blockly IR과 채점 결과를 비식별화된 연구 데이터세트에 포함합니다.',
    languageResearchTitle: '기본 언어', languageResearchBody: 'zh, en 같은 간단한 기본 언어 코드만 공유합니다.', timezoneResearchTitle: 'UTC 오프셋', timezoneResearchBody: '현재의 분 단위 오프셋만 공유하며 정확한 시간대 이름은 보내지 않습니다.', neverCollected: '브라우저 지문은 수집하지 않습니다.',
    participateStudy: '학술 연구에 참여', exitStudy: '나가기', studyTitle: '학술 연구 참여', studyIntro: 'HCR은 사람들이 로봇 프로그래밍을 배우는 과정을 살펴보는 학술 연구입니다. 데이터 사용 내용을 확인한 뒤 참여 여부를 선택하세요.',
    studyDeclinedTitle: '연구에 참여하지 않았습니다', studyDeclinedBody: '시뮬레이터 세션이나 플레이어 식별자는 생성되지 않았습니다. 이 페이지를 닫거나 연구 안내를 다시 확인할 수 있습니다.', reviewStudy: '연구 안내 다시 보기', closeApplication: '앱 닫기',
  },
  es: {
    language: 'IDIOMA', player: 'JUGADOR', tagline: 'Programa el brazo. Corta el cabello. Supera el reloj.',
    tutorial: 'Tutorial', tutorialBody: 'Aprende rutas de cuadrícula, ángulos de servo y cómo se conectan.', learn: 'Aprender →',
    lessons: 'Lecciones', lessonsBody: 'Diez lecciones Cutter Grid y ocho de servos, cada una con cuestionario y práctica Blockly obligatorios.', practise: 'Practicar →',
    solo: 'Práctica individual', soloBody: 'El siguiente reto se adapta a tu rendimiento.', start: 'Comenzar →',
    versus: 'Multijugador', versusBody: 'Mismo peinado y tiempo; gana quien más se acerque al objetivo.', play: 'Jugar →',
    backendConnected: 'SERVIDOR CONECTADO', offlinePractice: 'SIN CONEXIÓN · PRÁCTICA',
    defaultChallengeName: 'Recorte de la coronilla', defaultChallengeDescription: 'Elimina únicamente los once vóxeles resaltados de la coronilla y deja intacto el resto del cabello. Los cinco servos físicos comienzan a 90°. Mueve X · Base Yaw de 90° a 150° y mantén Y, Z, B y E en Home. Las lecciones dividen este barrido en pasos más breves.',
    requiredData: 'La puntuación en línea requiere enviar al servidor el programa Blockly compilado, el reto y los datos de puntuación.',
    researchChoice: 'Acepto que mis programas, puntuaciones, idioma principal y desfase UTC aproximado se usen en un conjunto de datos educativos desidentificado.',
    researchHint: 'Puedes desactivar por separado el idioma principal y el desfase UTC en «Más opciones». No recopilamos la huella del navegador ni el nombre exacto de la zona horaria.',
    dataSettings: 'Opciones de datos', privacyTitle: 'Cómo usar tus datos', privacyIntro: 'La puntuación en línea necesita algunos datos. Su uso para investigación se decide por separado.',
    necessaryTitle: 'Datos necesarios para puntuar', necessaryBody: 'Programa Blockly compilado, versión del reto y puntuación. Se usan siempre en la práctica y el modo multijugador en línea.',
    optionalTitle: 'Participación en la investigación', optionalBody: 'Programas y puntuaciones enviados, idioma principal y desfase UTC aproximado. No incluye la huella del navegador ni la zona horaria exacta.',
    necessaryOnly: 'Solo lo necesario', acceptResearch: 'Participar en el estudio', moreSettings: 'Más opciones', saveSettings: 'Guardar opciones',
    notNow: 'No participar', allowAllResearch: 'Permitir todos los datos del estudio', programResearchTitle: 'Programas y puntuaciones', programResearchBody: 'Incluye el Blockly IR enviado y su puntuación en el conjunto de datos desidentificado.',
    languageResearchTitle: 'Idioma principal', languageResearchBody: 'Comparte solo un código general, como zh o en.', timezoneResearchTitle: 'Desfase UTC', timezoneResearchBody: 'Comparte únicamente el desfase actual en minutos, no el nombre exacto de la zona horaria.', neverCollected: 'No recopilamos huellas del navegador.',
    participateStudy: 'Participar en el estudio académico', exitStudy: 'Salir', studyTitle: 'Participación en el estudio', studyIntro: 'HCR estudia cómo aprende la gente a programar robots. Revisa el uso de los datos y decide si quieres participar.',
    studyDeclinedTitle: 'Has decidido no participar', studyDeclinedBody: 'No se ha creado ninguna sesión del simulador ni identificador de jugador. Puedes cerrar esta página o volver a consultar la información del estudio.', reviewStudy: 'Revisar la información', closeApplication: 'Cerrar la aplicación',
  },
  fr: {
    language: 'LANGUE', player: 'JOUEUR', tagline: 'Programmez le bras. Taillez les cheveux. Battez le chrono.',
    tutorial: 'Tutoriel', tutorialBody: 'Découvrez les trajectoires, les angles des servos et leur relation.', learn: 'Apprendre →',
    lessons: 'Leçons', lessonsBody: 'Dix leçons Cutter Grid et huit sur les servos, chacune avec un quiz et un exercice Blockly obligatoires.', practise: 'Pratiquer →',
    solo: 'Entraînement solo', soloBody: 'Le prochain défi s’adapte à vos résultats.', start: 'Commencer →',
    versus: 'Multijoueur', versusBody: 'Même coiffure et même chrono ; le plus proche de la cible gagne.', play: 'Jouer →',
    backendConnected: 'SERVEUR CONNECTÉ', offlinePractice: 'HORS LIGNE · ENTRAÎNEMENT',
    defaultChallengeName: 'Coupe du sommet', defaultChallengeDescription: 'Retirez uniquement les onze voxels surlignés au sommet du crâne et laissez le reste des cheveux intact. Les cinq servomoteurs physiques démarrent à 90°. Faites passer X · Base Yaw de 90° à 150° en laissant Y, Z, B et E sur Home. Les leçons décomposent ce balayage en étapes plus courtes.',
    requiredData: 'La notation en ligne nécessite l’envoi au serveur du programme Blockly compilé, du défi et des scores.',
    researchChoice: 'J’accepte que mes programmes, mes scores, ma langue principale et mon décalage UTC approximatif soient utilisés dans un jeu de données pédagogique désidentifié.',
    researchHint: 'La langue principale et le décalage UTC peuvent être désactivés séparément dans « Plus de réglages ». Aucune empreinte du navigateur ni aucun nom précis de fuseau horaire ne sont recueillis.',
    dataSettings: 'Réglages des données', privacyTitle: 'Utilisation de vos données', privacyIntro: 'La notation en ligne nécessite certaines données. Leur utilisation pour la recherche fait l’objet d’un choix distinct.',
    necessaryTitle: 'Données nécessaires à la notation', necessaryBody: 'Programme Blockly compilé, version du défi et score. Ces données sont toujours utilisées pour l’entraînement et le multijoueur en ligne.',
    optionalTitle: 'Participation à la recherche', optionalBody: 'Programmes et scores envoyés, langue principale et décalage UTC approximatif. Aucune empreinte du navigateur ni aucun fuseau horaire précis.',
    necessaryOnly: 'Données nécessaires uniquement', acceptResearch: 'Participer à l’étude', moreSettings: 'Plus de réglages', saveSettings: 'Enregistrer',
    notNow: 'Ne pas participer', allowAllResearch: 'Autoriser toutes les données de recherche', programResearchTitle: 'Programmes et scores', programResearchBody: 'Ajoute le Blockly IR envoyé et le score obtenu au jeu de données désidentifié.',
    languageResearchTitle: 'Langue principale', languageResearchBody: 'Partage uniquement un code général tel que zh ou en.', timezoneResearchTitle: 'Décalage UTC', timezoneResearchBody: 'Partage uniquement le décalage actuel en minutes, sans nom précis de fuseau horaire.', neverCollected: 'Aucune empreinte du navigateur n’est recueillie.',
    participateStudy: 'Participer à l’étude universitaire', exitStudy: 'Quitter', studyTitle: 'Participation à l’étude', studyIntro: 'HCR étudie la façon dont les personnes apprennent à programmer des robots. Consultez l’utilisation prévue des données, puis choisissez de participer ou non.',
    studyDeclinedTitle: 'Vous avez choisi de ne pas participer', studyDeclinedBody: 'Aucune session du simulateur ni aucun identifiant de joueur n’a été créé. Vous pouvez fermer cette page ou relire les informations sur l’étude.', reviewStudy: 'Relire les informations', closeApplication: 'Fermer l’application',
  },
  ru: {
    language: 'ЯЗЫК', player: 'ИГРОК', tagline: 'Программируйте манипулятор. Стригите волосы. Побеждайте время.',
    tutorial: 'Обучение', tutorialBody: 'Изучите маршруты сетки, углы сервоприводов и связь двух способов управления.', learn: 'Учиться →',
    lessons: 'Уроки', lessonsBody: '10 уроков Cutter Grid и 8 уроков по сервоприводам с обязательной викториной и практикой Blockly.', practise: 'Практика →',
    solo: 'Одиночная практика', soloBody: 'Следующее задание подбирается по вашим результатам.', start: 'Начать →',
    versus: 'Сетевая игра', versusBody: 'Одинаковая причёска и время; побеждает самый точный результат.', play: 'Играть →',
    backendConnected: 'СЕРВЕР ПОДКЛЮЧЁН', offlinePractice: 'ОФЛАЙН · ПРАКТИКА',
    defaultChallengeName: 'Стрижка макушки', defaultChallengeDescription: 'Удалите только одиннадцать выделенных вокселей на макушке, не затрагивая остальные волосы. Все пять аппаратных сервоприводов начинают с 90°. Переместите X · Base Yaw с 90° на 150°, а Y, Z, B и E оставьте в положении Home. В уроках это движение разбито на короткие шаги.',
    requiredData: 'Для онлайн-оценки серверу необходимы скомпилированная программа Blockly, задание и данные оценки.',
    researchChoice: 'Я согласен использовать отправленные программы, оценки, основной язык и примерное смещение UTC в обезличенном наборе учебных данных.',
    researchHint: 'Основной язык и смещение UTC можно отключить по отдельности в разделе «Дополнительные настройки». Отпечаток браузера и точное название часового пояса не собираются.',
    dataSettings: 'Настройки данных', privacyTitle: 'Как использовать ваши данные', privacyIntro: 'Для онлайн-оценки нужны некоторые данные. Их использование в исследовании выбирается отдельно.',
    necessaryTitle: 'Данные для оценки', necessaryBody: 'Скомпилированная программа Blockly, версия задания и оценка. Эти данные всегда используются в онлайн-практике и сетевой игре.',
    optionalTitle: 'Участие в исследовании', optionalBody: 'Отправленные программы и оценки, основной язык и примерное смещение UTC. Без отпечатка браузера и точного названия часового пояса.',
    necessaryOnly: 'Только необходимые данные', acceptResearch: 'Участвовать в исследовании', moreSettings: 'Дополнительные настройки', saveSettings: 'Сохранить настройки',
    notNow: 'Не участвовать', allowAllResearch: 'Разрешить все исследовательские данные', programResearchTitle: 'Программы и оценки', programResearchBody: 'Добавляет отправленный Blockly IR и результат оценки в обезличенный набор данных.',
    languageResearchTitle: 'Основной язык', languageResearchBody: 'Передаёт только общий код языка, например zh или en.', timezoneResearchTitle: 'Смещение UTC', timezoneResearchBody: 'Передаёт только текущее смещение в минутах, без точного названия часового пояса.', neverCollected: 'Отпечаток браузера не собирается.',
    participateStudy: 'Участвовать в академическом исследовании', exitStudy: 'Выйти', studyTitle: 'Участие в исследовании', studyIntro: 'HCR изучает, как люди учатся программировать роботов. Ознакомьтесь с использованием данных и решите, хотите ли вы участвовать.',
    studyDeclinedTitle: 'Вы решили не участвовать', studyDeclinedBody: 'Сеанс симулятора и идентификатор игрока не созданы. Вы можете закрыть эту страницу или снова прочитать информацию об исследовании.', reviewStudy: 'Прочитать информацию ещё раз', closeApplication: 'Закрыть приложение',
  },
  de: {
    language: 'SPRACHE', player: 'SPIELER', tagline: 'Programmiere den Roboterarm. Schneide die Frisur. Schlage die Zeit.',
    tutorial: 'Tutorial', tutorialBody: 'Lerne Rasterpfade, Servowinkel und das Zusammenspiel beider Steuerungsarten kennen.', learn: 'Lernen →',
    lessons: 'Lektionen', lessonsBody: 'Zehn Lektionen zum Cutter Grid und acht zu Servowinkeln, jeweils mit Pflichtquiz und Blockly-Praxisaufgabe.', practise: 'Üben →',
    solo: 'Einzeltraining', soloBody: 'Die nächste Aufgabe passt sich deinem bisherigen Ergebnis an.', start: 'Starten →',
    versus: 'Mehrspieler', versusBody: 'Gleiche Frisur, gleiche Zeit. Wer dem Ziel am nächsten kommt, gewinnt.', play: 'Spielen →',
    backendConnected: 'BACKEND VERBUNDEN', offlinePractice: 'OFFLINE · TRAINING',
    defaultChallengeName: 'Scheitel trimmen', defaultChallengeDescription: 'Entferne nur die elf markierten Voxel am Oberkopf. Alle fünf Hardware-Servos starten bei 90°. Bewege X · Basis-Gierwinkel von 90° auf 150° und lasse Y, Z, B und E in der Home-Stellung.',
    requiredData: 'Für die Online-Bewertung werden das kompilierte Blockly-Programm sowie Aufgaben- und Bewertungsdaten an den Server gesendet.', researchChoice: 'Meine eingereichten Programme, Ergebnisse, Primärsprache und grobe UTC-Abweichung dürfen für deidentifizierte Lernforschung verwendet werden.', researchHint: 'Primärsprache und UTC-Abweichung lassen sich unter „Weitere Einstellungen“ getrennt ausschalten. Browser-Fingerabdrücke und genaue Zeitzonennamen werden nicht erhoben.',
    dataSettings: 'Dateneinstellungen', privacyTitle: 'Deine Datenauswahl', privacyIntro: 'Für die Online-Bewertung sind einige Daten erforderlich. Über ihre Forschungsnutzung entscheidest du getrennt.', necessaryTitle: 'Erforderliche Bewertungsdaten', necessaryBody: 'Kompiliertes Blockly-Programm, Aufgabenversion und Ergebnis. Für Online-Training und Mehrspieler immer aktiv.', optionalTitle: 'Optionale Lernforschung', optionalBody: 'Eingereichte Programme und Ergebnisse sowie Primärsprache und grobe UTC-Abweichung. Kein Browser-Fingerabdruck und keine genaue Zeitzone.', necessaryOnly: 'Nur erforderliche Daten', acceptResearch: 'Forschung erlauben', moreSettings: 'Weitere Einstellungen', saveSettings: 'Einstellungen speichern', notNow: 'Nicht teilnehmen', allowAllResearch: 'Alle Forschungsdaten erlauben', programResearchTitle: 'Programme und Ergebnisse', programResearchBody: 'Nimmt die eingereichte Blockly IR und das Ergebnis in den deidentifizierten Datensatz auf.', languageResearchTitle: 'Primärsprache', languageResearchBody: 'Teilt nur einen groben Sprachcode wie de oder en.', timezoneResearchTitle: 'UTC-Abweichung', timezoneResearchBody: 'Teilt nur die aktuelle Abweichung in Minuten, keinen genauen Zeitzonennamen.', neverCollected: 'Browser-Fingerabdrücke werden nie erhoben.', participateStudy: 'An der akademischen Studie teilnehmen', exitStudy: 'Beenden', studyTitle: 'Teilnahme an der akademischen Studie', studyIntro: 'HCR untersucht, wie Menschen Roboterprogrammierung lernen. Lies die Angaben zur Datennutzung und entscheide anschließend über deine Teilnahme.', studyDeclinedTitle: 'Du nimmst nicht an der Studie teil', studyDeclinedBody: 'Es wurden weder eine Simulatorsitzung noch eine Spielerkennung angelegt. Du kannst die Seite schließen oder die Studieninformationen erneut lesen.', reviewStudy: 'Studieninformationen erneut lesen', closeApplication: 'Anwendung schließen',
  },
};

const STORAGE_KEY = 'hcr.locale.v1';

interface LocalizationValue {
  locale: AppLocale;
  setLocale: (locale: AppLocale) => void;
  t: (key: MessageKey) => string;
}

const LocalizationContext = createContext<LocalizationValue | null>(null);
const DEFAULT_LOCALIZATION: LocalizationValue = {
  locale: 'en',
  setLocale: () => undefined,
  t: (key) => EN_MESSAGES[key],
};

export function LocalizationProvider({ children }: PropsWithChildren) {
  const [locale, setLocaleState] = useState<AppLocale>(loadLocale);
  const setLocale = (next: AppLocale) => {
    setLocaleState(next);
    try { globalThis.localStorage?.setItem(STORAGE_KEY, next); } catch { /* no-op */ }
  };
  useEffect(() => {
    document.documentElement.lang = locale;
  }, [locale]);
  const value = useMemo<LocalizationValue>(() => ({
    locale,
    setLocale,
    t: (key) =>
      MESSAGES[locale][key] ??
      FUNCTIONAL_MESSAGES[locale]?.[key] ??
      (locale === 'zh-HK' ? MESSAGES['zh-TW'][key] : undefined) ??
      EN_MESSAGES[key],
  }), [locale]);
  return <LocalizationContext.Provider value={value}>{children}</LocalizationContext.Provider>;
}

export function useLocalization(): LocalizationValue {
  const value = useContext(LocalizationContext);
  return value ?? DEFAULT_LOCALIZATION;
}

/** Returns keys that would visibly fall back to English for a non-English locale. */
export function missingMessageKeys(locale: Exclude<AppLocale, 'en'>): MessageKey[] {
  return (Object.keys(EN_MESSAGES) as MessageKey[]).filter((key) =>
    MESSAGES[locale][key] === undefined &&
    FUNCTIONAL_MESSAGES[locale]?.[key] === undefined &&
    !(locale === 'zh-HK' && MESSAGES['zh-TW'][key] !== undefined),
  );
}

function loadLocale(): AppLocale {
  try {
    const saved = globalThis.localStorage?.getItem(STORAGE_KEY);
    if (SUPPORTED_LOCALES.some(({ code }) => code === saved)) return saved as AppLocale;
  } catch { /* fall through */ }
  const language = globalThis.navigator?.language ?? 'en';
  if (/^zh-(HK|MO)/i.test(language)) return 'zh-HK';
  if (/^zh-TW/i.test(language)) return 'zh-TW';
  if (/^zh/i.test(language)) return 'zh-CN';
  const primary = language.split('-')[0]?.toLowerCase();
  return SUPPORTED_LOCALES.some(({ code }) => code === primary)
    ? (primary as AppLocale)
    : 'en';
}
