import type { RuckigLocalWasmModule } from './ruckigLocalWasm';

/**
 * The generated Community build lives outside the TypeScript module graph so
 * it can remain an audited, reproducible binary artifact.  It is staged into
 * Vite's public directory only by the explicit local build command.
 */
export const RUCKIG_LOCAL_WORKER_ASSETS = Object.freeze({
  modulePath: '/vendor/ruckig/hcr_ruckig_local.mjs',
  wasmFileName: 'hcr_ruckig_local.wasm',
  abiVersion: 'ruckig-local-5d-v2',
});

export interface RuckigLocalEmscriptenFactoryOptions {
  locateFile(fileName: string): string;
}

export type RuckigLocalEmscriptenFactory = (
  options: RuckigLocalEmscriptenFactoryOptions,
) => Promise<RuckigLocalWasmModule>;

export interface LoadRuckigLocalWorkerOptions {
  /**
   * Test-only factory injection. Production keeps this undefined and imports
   * the exact same-origin generated module below.
   */
  factory?: RuckigLocalEmscriptenFactory;
  /** Allows deterministic Worker tests without replacing global location. */
  workerLocation?: Pick<Location, 'href' | 'origin'>;
}

export class RuckigLocalWorkerLoadError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'RuckigLocalWorkerLoadError';
  }
}

/**
 * Loads the pinned local solver inside the planning Worker. No URL can come
 * from a challenge, Blockly program, profile, or remote configuration. The
 * Emscripten `locateFile` hook accepts exactly the audited wasm file and
 * refuses every other asset, preventing an accidental cloud/fallback loader.
 */
export async function loadRuckigLocalWorkerModule(
  options: LoadRuckigLocalWorkerOptions = {},
): Promise<RuckigLocalWasmModule> {
  const location = options.workerLocation ?? self.location;
  const moduleUrl = localAssetUrl(location, RUCKIG_LOCAL_WORKER_ASSETS.modulePath);
  const wasmUrl = localAssetUrl(
    location,
    RUCKIG_LOCAL_WORKER_ASSETS.modulePath.replace(/[^/]+$/, RUCKIG_LOCAL_WORKER_ASSETS.wasmFileName),
  );
  const factory = options.factory ?? await importLocalFactory(moduleUrl);
  try {
    return await factory({
      locateFile(fileName) {
        if (fileName !== RUCKIG_LOCAL_WORKER_ASSETS.wasmFileName) {
          throw new RuckigLocalWorkerLoadError(
            `Local Ruckig requested an unexpected asset: ${fileName}.`,
          );
        }
        return wasmUrl.href;
      },
    });
  } catch (error) {
    if (error instanceof RuckigLocalWorkerLoadError) throw error;
    throw new RuckigLocalWorkerLoadError(
      `Could not initialize the local Ruckig Worker module: ${error instanceof Error ? error.message : String(error)}`,
    );
  }
}

function localAssetUrl(
  location: Pick<Location, 'href' | 'origin'>,
  assetPath: string,
): URL {
  const url = new URL(assetPath, location.href);
  if (
    url.origin !== location.origin ||
    url.pathname !== assetPath ||
    url.search !== '' ||
    url.hash !== ''
  ) {
    throw new RuckigLocalWorkerLoadError('Local Ruckig asset URL is not the pinned same-origin path.');
  }
  return url;
}

async function importLocalFactory(moduleUrl: URL): Promise<RuckigLocalEmscriptenFactory> {
  // This file is generated by the explicit local audit/staging task rather
  // than bundled from npm. Keeping Vite out of this import also keeps its
  // asset graph from silently rewriting it to a CDN or data URL.
  const imported = await import(/* @vite-ignore */ moduleUrl.href) as {
    default?: unknown;
  };
  if (typeof imported.default !== 'function') {
    throw new RuckigLocalWorkerLoadError('Local Ruckig module does not export an Emscripten factory.');
  }
  return imported.default as RuckigLocalEmscriptenFactory;
}
