import type { AppLocale } from '../preferences/localization';
import type { Lesson } from './lessons';
import { isCourseLocale } from './internationalLessonLocalization';

type TutorialStep = Pick<Lesson, 'id' | 'title' | 'body' | 'hint'>;
type TutorialLocale = Exclude<AppLocale, 'en' | 'zh-CN' | 'zh-TW' | 'zh-HK'>;

interface TutorialCopy {
  titles: readonly string[];
  gridBody: (title: string) => string;
  bridgeBody: (title: string) => string;
  servoBody: (title: string) => string;
  details: Readonly<Record<string, string>>;
  hint: string;
}

const IDS = [
  'grid-welcome','grid-left','grid-up','grid-forward','grid-overlay','grid-complete-route','grid-test','grid-done',
  'bridge-welcome','bridge-grid-command','bridge-grid-ui','bridge-switch-servo','bridge-servo-command','bridge-home-angle','bridge-telemetry','bridge-return-grid','bridge-done',
  'welcome','first-block','absolute','test','head','repeat-noop','repeat-sweep','done',
] as const;

const COPY: Record<TutorialLocale, TutorialCopy> = {
  ja: {
    titles:['サーボではなくカッターを動かす','最初の移動を追加','2本目の軸へ移動','2つ目のブロックで残りの高さを上る','実行前にグリッドを読む','検証済み経路を完成','経路を計画してテスト','Gridレッスンの準備完了','同じアーム、2段階の制御','まず空間上の意図を表す','Gridの情報を読む','サーボ角度へ切り替える','関節の目標を直接指定','Homeはすべて90°','2つの表示をテレメトリーで結ぶ','作業領域が別々か確認','課題に合う制御方式を選ぶ','プログラムを書いて切る','最初の命令を追加','角度は絶対値','テストは即時評価','頭部への衝突で停止','同じ角度の繰り返し','往復する繰り返し','言語の基本を習得'],
    gridBody:(t)=>`${t}。固定ワールド座標軸を使い、カッターの空間経路を作ります。経路計画器が安全な関節軌道を計算します。`, bridgeBody:(t)=>`${t}。Cutter Gridの空間座標と、ハードウェアへ送る絶対サーボ角度を同じ作業画面で比較します。`, servoBody:(t)=>`${t}。ライブ角度、ブロックの強調表示、衝突メッセージを確認しながら操作してください。`,
    details:{'grid-left':'「左へ 3ボクセル」を追加します。左は固定ワールド座標の−Xです。','grid-up':'その下に「上へ 6ボクセル」を接続します。上は+Yです。','grid-forward':'続けて「上へ 2ボクセル」を接続します。「上へ 8」を1つではなく2つのブロックに分けます。各ブロックは1回の滑らかな動作として計画され、長い動作ほど狙った直線から曲がるためです。','grid-complete-route':'残りの6ブロック、前1、上1、前1、上1、前6、前1を追加します。左3 → 上6 → 上2 → 前1 → 上1 → 前1 → 上1 → 前6 → 前1の9ブロックで、余分に切らず11個の対象ボクセルを除去します。','grid-test':'「テスト」を押します。Cutter Gridは経路全体を計画してからアニメーションなしで実行し、カッターが通過した経路を採点します。','bridge-grid-command':'Cutter Gridで「左へ1」を追加します。','bridge-switch-servo':'待機中にBlockly上部の切替でサーボ角度を選びます。','bridge-servo-command':'サーボ分類から絶対角度の設定ブロックを追加します。','bridge-home-angle':'X、Y、Z、B、EのハードウェアHome角度はすべて90°です。','first-block':'左側のサーボ分類から角度設定ブロックを作業領域へ移します。','absolute':'ベースヨーを−55°に設定します。これは相対移動ではなく絶対目標です。','test':'「テスト」はアニメーションなしで数ミリ秒以内に評価します。動きを見る場合は「実行」を使います。','head':'角度を0°にしてテストし、安全な最終姿勢で停止することを確認したら−55°へ戻します。','repeat-noop':'−55°への同じ設定を繰り返しても、2回目以降は移動しません。','repeat-sweep':'繰り返しの中に−55°と−38°の2つの設定を置き、往復運動を作ります。'}, hint:'表示された値とブロック順を確認してから次へ進んでください。',
  },
  ko: {
    titles:['서보가 아니라 커터 이동','첫 이동 추가','두 번째 축으로 이동','두 번째 블록으로 나머지 높이 오르기','실행 전 그리드 확인','검증 경로 완성','경로 계획과 테스트','Grid 레슨 준비 완료','하나의 로봇 팔, 두 제어 수준','공간 의도부터 표현','Grid 정보 확인','서보 각도로 전환','관절 목표 직접 지정','Home은 모두 90°','텔레메트리로 두 관점 연결','작업 영역 분리 확인','과제에 맞는 제어 선택','프로그램으로 절단','첫 명령 추가','각도는 절대값','테스트는 즉시 평가','머리 충돌 시 정지','같은 각도 반복','왕복 반복 만들기','기본 언어 습득 완료'],
    gridBody:(t)=>`${t}. 고정 월드 좌표축으로 커터의 공간 경로를 만들면 경로 계획기가 안전한 관절 궤적을 계산합니다.`, bridgeBody:(t)=>`${t}. Cutter Grid 좌표와 하드웨어에 전송되는 절대 서보 각도를 같은 작업 화면에서 비교하세요.`, servoBody:(t)=>`${t}. 실시간 각도, 강조된 블록과 충돌 메시지를 확인하며 진행하세요.`,
    details:{'grid-left':'‘왼쪽 3복셀’을 추가하세요. 왼쪽은 고정 월드의 −X입니다.','grid-up':'아래에 ‘위 6복셀’을 연결하세요. 위는 +Y입니다.','grid-forward':'이어서 ‘위 2복셀’을 연결하세요. ‘위 8’ 한 블록이 아니라 두 블록을 사용합니다. 각 블록은 하나의 부드러운 움직임으로 계획되며 긴 움직임일수록 목표 직선에서 더 휘기 때문입니다.','grid-complete-route':'나머지 6개 블록인 앞1, 위1, 앞1, 위1, 앞6, 앞1을 추가하세요. 왼쪽3 → 위6 → 위2 → 앞1 → 위1 → 앞1 → 위1 → 앞6 → 앞1의 9개 블록 경로는 불필요한 절단 없이 목표 복셀 11개를 제거합니다.','grid-test':'‘테스트’를 누르세요. Cutter Grid는 전체 궤적을 먼저 계획한 뒤 애니메이션 없이 실행하고 커터가 지나간 경로를 채점합니다.','bridge-grid-command':'Cutter Grid에서 ‘왼쪽1’을 추가하세요.','bridge-switch-servo':'대기 상태에서 Blockly 위쪽 전환 버튼으로 서보 각도를 선택하세요.','bridge-servo-command':'서보 범주에서 절대 각도 설정 블록을 추가하세요.','bridge-home-angle':'X, Y, Z, B, E의 하드웨어 Home 각도는 모두 90°입니다.','first-block':'왼쪽 서보 범주에서 각도 설정 블록을 작업 영역으로 끌어오세요.','absolute':'베이스 요를 −55°로 설정하세요. 상대 이동이 아니라 절대 목표입니다.','test':'‘테스트’는 애니메이션 없이 즉시 평가합니다. 움직임을 보려면 ‘실행’을 사용하세요.','head':'각도를 0°로 테스트해 안전 자세에서 정지하는지 확인한 뒤 −55°로 되돌리세요.','repeat-noop':'같은 −55° 설정을 반복하면 두 번째부터는 움직이지 않습니다.','repeat-sweep':'반복 안에 −55°와 −38° 설정을 차례로 넣어 왕복 운동을 만드세요.'}, hint:'표시된 값과 블록 순서를 확인한 뒤 다음 단계로 이동하세요.',
  },
  es: {
    titles:['Mueve el cortador, no los servos','Añade el primer movimiento','Usa un segundo eje','Completa el ascenso con un segundo bloque','Lee la cuadrícula antes de ejecutar','Completa la ruta certificada','Planifica y prueba la ruta','Preparado para las lecciones Grid','Un brazo, dos niveles de control','Expresa primero la intención espacial','Lee la información de Grid','Cambia a ángulos de servo','Indica el objetivo articular','Home significa 90° en todos los motores','Une ambas vistas con telemetría','Comprueba los espacios de trabajo','Elige el control adecuado','Tú programas; el brazo corta','Añade la primera orden','Los ángulos son absolutos','Probar evalúa al instante','La cabeza detiene el brazo','Repetir el mismo ángulo','Crear un barrido repetido','Ya conoces el lenguaje básico'],
    gridBody:(t)=>`${t}. Describe la ruta espacial del cortador con ejes fijos del mundo; el planificador calcula una trayectoria articular segura.`, bridgeBody:(t)=>`${t}. Compara las coordenadas de Cutter Grid con los ángulos absolutos que recibiría el hardware en el mismo banco de trabajo.`, servoBody:(t)=>`${t}. Observa los ángulos en vivo, el bloque resaltado y cualquier aviso de colisión.`,
    details:{'grid-left':'Añade «Izquierda 3 vóxeles». Izquierda corresponde a −X en el mundo.','grid-up':'Conecta «Arriba 6 vóxeles» debajo. Arriba corresponde a +Y.','grid-forward':'Conecta después «Arriba 2 vóxeles». Usa dos bloques en lugar de uno de «Arriba 8»: el planificador ejecuta cada bloque como un movimiento suave y un tramo largo se curva más lejos de la línea de celdas deseada.','grid-complete-route':'Añade los seis bloques restantes: Adelante1, Arriba1, Adelante1, Arriba1, Adelante6 y Adelante1. La ruta de nueve bloques Izquierda3 → Arriba6 → Arriba2 → Adelante1 → Arriba1 → Adelante1 → Arriba1 → Adelante6 → Adelante1 elimina los 11 vóxeles objetivo sin cortes adicionales.','grid-test':'Pulsa «Probar». Cutter Grid planifica primero la trayectoria completa, la ejecuta sin animación y puntúa el recorrido del cortador.','bridge-grid-command':'Añade «Izquierda1» en Cutter Grid.','bridge-switch-servo':'Con la simulación en espera, elige Ángulos de servo sobre Blockly.','bridge-servo-command':'Añade desde Servos un bloque que fije un ángulo absoluto.','bridge-home-angle':'Los ángulos Home de X, Y, Z, B y E son todos 90°.','first-block':'Arrastra un bloque de ajuste de ángulo desde la categoría Servos.','absolute':'Fija Giro de la base en −55°. Es un destino absoluto, no un desplazamiento.','test':'«Probar» evalúa en milisegundos y sin animación. Usa «Ejecutar» para observar el movimiento.','head':'Prueba 0°, observa la parada en la última postura segura y vuelve a −55°.','repeat-noop':'Repetir el mismo destino −55° no produce movimiento después de la primera vuelta.','repeat-sweep':'Coloca −55° y −38° dentro de Repetir para crear un movimiento de ida y vuelta.'}, hint:'Comprueba los valores indicados y el orden de los bloques antes de continuar.',
  },
  fr: {
    titles:['Déplacez le couteau, pas les servos','Ajoutez le premier déplacement','Utilisez un deuxième axe','Terminez la montée avec un second bloc','Lisez la grille avant l’exécution','Terminez la trajectoire certifiée','Planifiez et testez la trajectoire','Prêt pour les leçons Grid','Un bras, deux niveaux de commande','Exprimez d’abord l’intention spatiale','Lisez les informations de Grid','Passez aux angles de servo','Fixez directement la cible articulaire','Home place tous les moteurs à 90°','Reliez les deux vues par télémétrie','Vérifiez les espaces de travail','Choisissez la commande adaptée','Vous programmez, le bras coupe','Ajoutez la première commande','Les angles sont absolus','Tester évalue immédiatement','La tête arrête le bras','Répéter le même angle','Créer un balayage répété','Les bases du langage sont acquises'],
    gridBody:(t)=>`${t}. Décrivez la trajectoire spatiale du couteau dans le repère fixe du monde ; le planificateur calcule un mouvement articulaire sûr.`, bridgeBody:(t)=>`${t}. Comparez les coordonnées de Cutter Grid aux angles absolus envoyés au matériel, dans le même espace de travail.`, servoBody:(t)=>`${t}. Suivez les angles en direct, le bloc surligné et les éventuels messages de collision.`,
    details:{'grid-left':'Ajoutez « Gauche 3 voxels ». Gauche correspond à −X dans le repère du monde.','grid-up':'Raccordez « Haut 6 voxels » en dessous. Haut correspond à +Y.','grid-forward':'Raccordez ensuite « Haut 2 voxels ». Utilisez deux blocs plutôt qu’un seul « Haut 8 » : chaque bloc est planifié comme un mouvement fluide, et un long trajet s’écarte davantage de la ligne de cellules visée.','grid-complete-route':'Ajoutez les six blocs restants : Avant1, Haut1, Avant1, Haut1, Avant6 et Avant1. La trajectoire de neuf blocs Gauche3 → Haut6 → Haut2 → Avant1 → Haut1 → Avant1 → Haut1 → Avant6 → Avant1 retire les 11 voxels cibles sans coupe supplémentaire.','grid-test':'Appuyez sur « Tester ». Cutter Grid planifie d’abord toute la trajectoire, l’exécute sans animation et note le passage du couteau.','bridge-grid-command':'Ajoutez « Gauche1 » dans Cutter Grid.','bridge-switch-servo':'Lorsque la simulation est en attente, choisissez Angles des servos au-dessus de Blockly.','bridge-servo-command':'Ajoutez un bloc d’angle absolu depuis la catégorie Servomoteurs.','bridge-home-angle':'Les angles Home de X, Y, Z, B et E valent tous 90°.','first-block':'Faites glisser un bloc de réglage d’angle depuis la catégorie Servomoteurs.','absolute':'Réglez le lacet de la base sur −55°. Il s’agit d’une cible absolue, pas d’un déplacement.','test':'« Tester » évalue en quelques millisecondes sans animation. Utilisez « Exécuter » pour observer le mouvement.','head':'Testez 0°, observez l’arrêt à la dernière pose sûre, puis revenez à −55°.','repeat-noop':'Répéter la même cible −55° ne produit plus de mouvement après le premier passage.','repeat-sweep':'Placez −55° puis −38° dans Répéter pour créer un mouvement aller-retour.'}, hint:'Vérifiez les valeurs indiquées et l’ordre des blocs avant de poursuivre.',
  },
  ru: {
    titles:['Перемещайте резак, а не сервоприводы','Добавьте первое перемещение','Используйте вторую ось','Завершите подъём вторым блоком','Проверьте сетку перед запуском','Завершите проверенный маршрут','Спланируйте и проверьте маршрут','Можно переходить к урокам Grid','Один манипулятор, два уровня управления','Сначала задайте пространственное намерение','Прочитайте данные Grid','Переключитесь на углы сервоприводов','Задайте цель сустава напрямую','Home означает 90° для всех приводов','Свяжите два представления телеметрией','Проверьте раздельные рабочие области','Выберите подходящее управление','Вы программируете, манипулятор стрижёт','Добавьте первую команду','Углы задаются абсолютно','Проверка выполняется мгновенно','Голова останавливает манипулятор','Повторение одного угла','Повторяющееся движение','Основы языка освоены'],
    gridBody:(t)=>`${t}. Опишите пространственный маршрут резака в фиксированных мировых осях; планировщик рассчитает безопасную траекторию суставов.`, bridgeBody:(t)=>`${t}. Сравните координаты Cutter Grid с абсолютными углами, которые получит оборудование, в одной рабочей области.`, servoBody:(t)=>`${t}. Следите за текущими углами, выделенным блоком и сообщениями о столкновении.`,
    details:{'grid-left':'Добавьте «Влево 3 вокселя». Влево соответствует мировой оси −X.','grid-up':'Подключите снизу «Вверх 6 вокселей». Вверх соответствует +Y.','grid-forward':'Затем подключите «Вверх 2 вокселя». Используйте два блока вместо одного «Вверх 8»: планировщик выполняет каждый блок как одно плавное движение, а длинный участок сильнее отклоняется от нужной прямой линии ячеек.','grid-complete-route':'Добавьте оставшиеся шесть блоков: Вперёд1, Вверх1, Вперёд1, Вверх1, Вперёд6 и Вперёд1. Маршрут из девяти блоков Влево3 → Вверх6 → Вверх2 → Вперёд1 → Вверх1 → Вперёд1 → Вверх1 → Вперёд6 → Вперёд1 удаляет 11 целевых вокселей без лишних срезов.','grid-test':'Нажмите «Проверить». Cutter Grid сначала планирует весь маршрут, затем выполняет его без анимации и оценивает путь резака.','bridge-grid-command':'Добавьте «Влево1» в Cutter Grid.','bridge-switch-servo':'В режиме ожидания выберите углы сервоприводов над Blockly.','bridge-servo-command':'Добавьте из категории сервоприводов блок абсолютного угла.','bridge-home-angle':'Углы Home для X, Y, Z, B и E равны 90°.','first-block':'Перетащите блок задания угла из категории сервоприводов.','absolute':'Установите рыскание основания на −55°. Это абсолютная цель, а не смещение.','test':'«Проверить» оценивает программу за миллисекунды без анимации. Для наблюдения используйте «Запустить».','head':'Проверьте 0°, дождитесь остановки в последней безопасной позе и верните −55°.','repeat-noop':'Повтор одной цели −55° не вызывает движения после первого прохода.','repeat-sweep':'Поместите −55° и −38° внутрь повтора, чтобы получить движение туда и обратно.'}, hint:'Перед продолжением проверьте указанные значения и порядок блоков.',
  },
  de: {
    titles:['Bewege den Cutter, nicht die Servos','Erste Bewegung hinzufügen','Zweite Achse nutzen','Restliche Höhe mit einem zweiten Block erklimmen','Raster vor dem Start lesen','Zertifizierten Pfad vervollständigen','Pfad planen und testen','Bereit für die Grid-Lektionen','Ein Arm, zwei Steuerungsebenen','Zuerst die räumliche Absicht ausdrücken','Grid-Informationen lesen','Zu Servowinkeln wechseln','Gelenkziel direkt vorgeben','Home bedeutet überall 90°','Beide Ansichten per Telemetrie verbinden','Getrennte Arbeitsbereiche prüfen','Passende Steuerung wählen','Du programmierst, der Arm schneidet','Ersten Befehl hinzufügen','Winkel sind absolute Ziele','Testen wertet sofort aus','Der Kopf stoppt den Arm','Denselben Winkel wiederholen','Wiederholten Schwenk erzeugen','Grundlagen der Sprache beherrscht'],
    gridBody:(t)=>`${t}. Beschreibe den räumlichen Cutter-Pfad in festen Weltachsen; der Planer berechnet daraus eine sichere Gelenktrajektorie.`, bridgeBody:(t)=>`${t}. Vergleiche Cutter-Grid-Koordinaten und absolute Hardware-Servowinkel in derselben Arbeitsansicht.`, servoBody:(t)=>`${t}. Beobachte Live-Winkel, markierte Blöcke und mögliche Kollisionsmeldungen.`,
    details:{'grid-left':'Füge „Links 3 Voxel“ hinzu. Links entspricht der Weltachse −X.','grid-up':'Verbinde darunter „Oben 6 Voxel“. Oben entspricht +Y.','grid-forward':'Verbinde danach „Oben 2 Voxel“. Verwende zwei Blöcke statt einmal „Oben 8“: Der Planer führt jeden Block als eine gleichmäßige Bewegung aus, und ein langer Abschnitt weicht stärker von der gewünschten geraden Zelllinie ab.','grid-complete-route':'Füge die übrigen sechs Blöcke hinzu: Vorwärts1, Oben1, Vorwärts1, Oben1, Vorwärts6 und Vorwärts1. Der Pfad aus neun Blöcken Links3 → Oben6 → Oben2 → Vorwärts1 → Oben1 → Vorwärts1 → Oben1 → Vorwärts6 → Vorwärts1 entfernt die 11 Zielvoxel ohne zusätzlichen Schnitt.','grid-test':'Drücke „Testen“. Cutter Grid plant zuerst die vollständige Trajektorie, führt sie ohne Animation aus und bewertet den Weg des Cutters.','bridge-grid-command':'Füge in Cutter Grid „Links1“ hinzu.','bridge-switch-servo':'Wähle im Bereitschaftszustand oberhalb von Blockly den Modus Servowinkel.','bridge-servo-command':'Füge aus der Servo-Kategorie einen Block für einen absoluten Winkel hinzu.','bridge-home-angle':'Die Home-Winkel von X, Y, Z, B und E betragen jeweils 90°.','first-block':'Ziehe einen Winkelblock aus der Servo-Kategorie in den Arbeitsbereich.','absolute':'Setze den Basis-Gierwinkel auf −55°. Das ist ein absolutes Ziel, keine relative Drehung.','test':'„Testen“ wertet in Millisekunden ohne Animation aus. Nutze „Ausführen“, um die Bewegung zu sehen.','head':'Teste 0°, beobachte den Stopp in der letzten sicheren Pose und stelle danach wieder −55° ein.','repeat-noop':'Das wiederholte Ziel −55° erzeugt nach dem ersten Durchlauf keine weitere Bewegung.','repeat-sweep':'Setze −55° und −38° in die Wiederholung, um eine Hin-und-her-Bewegung zu erzeugen.'}, hint:'Prüfe vor dem nächsten Schritt die angegebenen Werte und die Blockreihenfolge.',
  },
};

export function localizeInternationalTutorialStep<T extends TutorialStep>(step: T, locale: AppLocale): T {
  if (!isCourseLocale(locale)) return step;
  const index = IDS.indexOf(step.id as (typeof IDS)[number]);
  if (index < 0) return step;
  const copy = COPY[locale];
  const title = copy.titles[index];
  const categoryBody = step.id.startsWith('grid-') ? copy.gridBody(title) : step.id.startsWith('bridge-') ? copy.bridgeBody(title) : copy.servoBody(title);
  const body = copy.details[step.id] ? `${categoryBody} ${copy.details[step.id]}` : categoryBody;
  return { ...step, title, body, ...(step.hint ? { hint: copy.hint } : {}) };
}
